export const ELEMENTS = {
    pagePa: "https://rns-hmlg.cnseg.org.br/RegistroNacionalSinistroWeb/login.jsp",
    emailInputPa: '[name="login"]',
    passwordInputPa: '[name="senha"]',
    iconButtonPa: '#submitLogin',
    msgConfirmPa: '[class="azul"]',
    conSinPa: 'https://rns-hmlg.cnseg.org.br/RegistroNacionalSinistroWeb/sinistropatrimonial/abrirConsultaPatrimonial.action?tipoSinistro=3&tipoRamoFaturamento=3',
    conSinConfirmPa: '[class=bgTopoForm]>h3',
    tipoConPa: '#listaTipoConsultaPatrimonial+div>:nth-child(2)',
    escCnpjPa: '#listaTipoConsultaPatrimonial+div>ul>li:nth-child(2)>a',
    digCnpjPa: '#cnpj',
    escCpfPa: '#listaTipoConsultaPatrimonial+div>ul>li:nth-child(3)>a',
    digCpfPa: '#cpf',
    escEndOcorrPa: '#listaTipoConsultaPatrimonial+div>ul>li:nth-child(4)>a',
    digCepOcorrPa: '#cepEnderecoOcorrencia',
    digNumOcorrPa: '#numeroEnderecoOcorrencia',
    escEndSegPa: '#listaTipoConsultaPatrimonial+div>ul>li:nth-child(5)>a',
    digCepSegPa: '#cepEnderecoSegurado',
    digNumSegPa: '#numeroEnderecoSegurado',
    escMatrizCnpjPa: '#listaTipoConsultaPatrimonial+div>ul>li:nth-child(6)>a',
    digMatrizCnpjPa: '#matrizCNPJ',
    btnConsultarPa: '#consultarPatrimonial',
    resultConsultaPa: '.tab-eventos caption',
    resultConsultaVaziaPa: '[class=container]>[class=conteudo]>#erroJson2>span>span'
}